gui:
  nerdFontsVersion: "3"
git:
  parseEmoji: true
  # paging:
  #   externalDiffCommand: difft --color=always --display=inline
keybinding:
  commits:
    revertCommit: <c-v>
    viewResetOptions: t
